project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    right:
      - index.qmd
      - about.qmd
      - icon: envelope
        href: mailto:mahamoud.koureichi@gmail.com

html:
    theme: lumen
    css: styles.css

editor: visual

