project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - index.qmd
      - icon: github
        href: https://github.com/
  html:
    theme: lumen
    css: styles.css

editor: visual

